### ISSUE TITLE
Plugin not loading on OS X Mavericks

### ISSUE THREAD

**Issue by sleepyarmistice** [dave-atx/homebridge-platform-smartac#1]
This plugin isn't loading on my home bridge installation running on OS X 10.9.5  Any help you can give would be greatly appreciated. Here's the error it gives:

====================
[7/10/2017, 4:38:18 PM] ERROR LOADING PLUGIN homebridge-platform-smartac:
[7/10/2017, 4:38:18 PM] /usr/local/lib/node_modules/homebridge-platform-smartac/index.js:82
  async auth() {
        ^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:128:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
[7/10/2017, 4:38:18 PM] ====================

**Comment by dave-atx** [comment]
Hi, looks like you're probably on a nodejs version that's not recent enough to support async / await. Try upgrading to nodejs v7.6 or higher and give it another try.

**Comment by sleepyarmistice** [comment]
That did it. Thanks!

**Comment by dave-atx** [comment]
Great!
