### ISSUE TITLE
Modlet/SmartAC went down this morning and now AC is stuck updating

### ISSUE THREAD

**Issue by jsaltzman** [dave-atx/homebridge-platform-smartac#10]
This morning the Modlet service went down. I contacted tech support to confirm it was down. The app did not work nor the website. Now it is back online but my Modlet is stuck "updating" in the Home app. Any idea what the issue is? Please let me know if you need additional info to troubleshoot.

**Comment by dave-atx** [comment]
If you restart the homebridge service, that should kick things back
into gear. If your phone still doesn’t pick that up, you can restart
that as well.

**Comment by jsaltzman** [comment]
Fixed. Does homebridge and or the smartAC often need a reboot? It’s a bit
of a process to do when not on my network (no vpn currently setup).

**Comment by elesueur** [comment]
Seems like the plugin doesn't handle well when the ThinkEco API returns a gateway timeout (which is usually an HTML response). I noticed that my entire homebridge system seems to become unresponsive periodically, and when I look back through the logs, I see

`
[2019-9-1 00:18:12] [ThinkEco SmartAC Platform] api updating thermostat status...
(node:454) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>:null:null)
    at ThinkEcoAPI.getThermostats (/usr/local/lib/node_modules/homebridge-platform-smartac/index.js:121:36)
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:118:7)

(node:454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:454) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

The unexpected < is the opening bracket of the `<html>` tag that is returned.

The smart AC plugin code needs to be improved to handle the case when the API does not return JSON.
