### ISSUE TITLE
No response from smartac plugs, restart does not fix issue

### ISSUE THREAD

**Issue by jsaltzman** [dave-atx/homebridge-platform-smartac#11]
My smartac plugs have stopped working after a week or two of working. I have restarted my home bridge docker container and that did not fix the issue. I also restarted my server running the container to see if that would fix the issue. I am happy to help you troubleshoot this.

**Comment by jsaltzman** [comment]
Adding my log below:


[8/3/2019, 11:30:20 AM] Loading 1 platforms...

[8/3/2019, 11:30:20 AM] [ThinkEco SmartAC Platform] Initializing SmartAC platform...

[8/3/2019, 11:30:20 AM] Loading 0 accessories...

[8/3/2019, 11:30:20 AM] [ThinkEco SmartAC Platform] api updating thermostat status...

[8/3/2019, 11:30:20 AM] [ThinkEco SmartAC Platform] api logging in...

(node:1630) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0

    at JSON.parse (<anonymous>)

    at ThinkEcoAPI.getThermostats (/usr/local/lib/node_modules/homebridge-platform-smartac/index.js:121:36)

    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:1630) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:1630) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jsaltzman** [comment]
I cannot be sure, but I think this was caused by the fact that the smartac plugin gets uninstalled or deleted each time the homebridge container is restarted. I fixed this by adding the command to install the smartac npm package to homebridge on homebridge startup.
