### ISSUE TITLE
plugin won't load

### ISSUE THREAD

**Issue by ab1470** [dave-atx/homebridge-platform-smartac#2]
I can't get the plugin to load. Here's the relevant error log:

```
[7/20/2017, 10:10:43 PM] ====================
[7/20/2017, 10:10:43 PM] ERROR LOADING PLUGIN homebridge-platform-smartac:
[7/20/2017, 10:10:43 PM] /usr/local/lib/node_modules/homebridge-platform-smartac/index.js:82
  async auth() {
        ^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
[7/20/2017, 10:10:43 PM] ====================
[7/20/2017, 10:10:44 PM] Loaded plugin: homebridge-platform-wemo
[7/20/2017, 10:10:44 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[7/20/2017, 10:10:44 PM] ---
[7/20/2017, 10:10:44 PM] Loaded config.json with 2 accessories and 2 platforms.
[7/20/2017, 10:10:44 PM] ---
[7/20/2017, 10:10:44 PM] Loading 2 platforms...
[7/20/2017, 10:10:44 PM] [WeMo Platform] Initializing BelkinWeMo platform...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'SmartAC' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
```

I verified my config.json on jsonlint.com. Also, I've successfully gotten Homebridge to work with other accessories, so I know my setup is sound. 

Any ideas?

**Comment by dave-atx** [comment]
It looks like the issue is that you're using an earlier version of Node than the plugin requires. You should upgrade to Node v7.6 or higher and you should be good to go.

(The plugin uses async / await, which was introduced in v7.6).
